### ISSUE TITLE
remote crash, reproducible

### ISSUE THREAD

**Issue by warmstarter** [kruton/tinyfugue#12]
I can reliably remotely crash this version of TF. There's already one version patched, but I would like to reliably disclose this to you, please tell me how best to contact.

**Comment by warmstarter** [comment]
This is fixed in Sketch's fork of this repo. I'll try to get in touch with him about sending a pull request, and if not I'll work to make one. Managed to patch the same issue on TF-rebirth using the modifications on Sketch's fork, and it worked out well despite being a very diverged target. Should be relatively easy for here.

**Comment by warmstarter** [comment]
Also note, this relates to the backspace bug reported in 2012. That's creating strange characters that can cause a crash either locally or remotely. Usually it just makes garbled text, but I can reliably make it crash.

**Comment by kruton** [comment]
Sure. I don't think anyone has sent a pull request here ever.

**Comment by warmstarter** [comment]
This is resolved in the Pull Request that just got merge.
