### ISSUE TITLE
Color Crash Bug

### ISSUE THREAD

**Issue by warmstarter** [kruton/tinyfugue#17]
Found an easy way to crash TinyFugue.

This would be a pretty standard way to set colors in my status bar:

/set vw_tablist_fg_world_attrs=@{Cyellow,Cbgrgb001}

But if I just set it to a non-existent color:

/set vw_tablist_fg_world_attrs=@{Ctestyellow,Cbgrgb001}

And then change my fgworld to trigger the color change in the status bar, TF dumps core. Presumably similar would happen with any way of setting that invalid color. Looks like colors are just being passed for evaluation rather than sanity checked.

Haven't yet tested if I can get a MUSH to remotely crash TF with this bug, but seems likely.

Tagging @Sketch in case he's not watching here.

**Comment by kruton** [comment]
What reads `vw_tablist_...` stuff? For instance `/set status_attr=Ctestblue` just results in an error message saying it's an invalid color.

**Comment by warmstarter** [comment]
It's coming from this vwstatus.tf which basically handles the status bar for the vworld.tf that @sketch made. So if you make the change I listed, nothing happens at first. When you switch over to a new world, the fg_world changes, which changes the attrs on the previous fg_world and the new fg_world, and causes an immediate crash.

https://github.com/warmstarter/tinyfugue-scripts/blob/main/lib/vwstatus.tf

vw_build_tabs is the relevant macro

I haven't had a chance to fully go through this yet. Was both a note to myself as well as seeing if others had thoughts.

There may be more to it, but these seem like the relevant lines that might make it slightly more complex that just setting status_attr:

Early on setting the color:
```
/test _ret_item := strcat(_ret_item, vw_tablist_fg_world_attrs )
```

Later on parsing everything:
```
        /test _dret:=decode_attr(_ret) %;\
        /test _avail_len:=vw_get_tablist_size() %;\
        /if (strlen(_dret) > _avail_len) \
                /if (vw_exists(fg_world())) \
                        /test _fg_loc:=strstr(_dret, vw_tab_name(fg_world())) %;\
                /else \
                        /test _fg_loc:=strstr(_dret, fg_world()) %;\
                /endif %;\
                /test _cutoff:=strchr(_dret, "|[", _fg_loc - _avail_len/2 > 0 ? _fg_loc - _avail_len/2 : 0) %;\
        /else \
                /test _cutoff:=0 %;\
        /endif %;\
        /return tolower(substr({_dret}, _cutoff))
```

and then being applied like this:

```
/def -i vw_update_activity = \
    /status_edit -r0 vw_tabs
```

vwstatus.tf requires socket.tf and status.tf, but I don't think the problem is in that code. vwstatus.tf is listed as requiring vworld.tf, but actually doesn't it just includes features that make sense to run together. So if you wanted to try it out yourself, you would just need to load socket.tf and vwstatus.tf, and just make sure you're not running activity_status*.tf as the status bar can only have one variable length per line. They can technically be run together on different lines, and I did so during the initial debugging, but as is it's not setup that way.

**Comment by warmstarter** [comment]
Actually, my mistake, it will require vworld.tf for one small part. I'm going to work to separate that out better, but to try it for now you need those four .tf files, though it seems fairly clear the problem is getting triggered by vwstatus.tf

**Comment by warmstarter** [comment]
Oh, and I tested it also on the original 50b8 code and the issue has been there the whole time, not anything new. I also checked in on another TF codebase and they also have this error.

**Comment by warmstarter** [comment]
Here it is .....

```
/eval /set colorcrash=@{CbgblackCRASH}Crash!
/test colorcrash := decode_attr(colorcrash)
```

@Sketch

**Comment by warmstarter** [comment]
Ok, here's a hint, this also works. Given that the @{ is unmatched, it shouldn't even be attempting anything.

```
/eval /set colorcrash=@{CbgblackCRASH
/test colorcrash := decode_attr(colorcrash)
```

**Comment by warmstarter** [comment]
https://pastebin.com/JxsizRcG

**Comment by kruton** [comment]
Yeah, I think the minimal test case is just:
```
/test decode_attr("@{")
```

So it ends up at this line which calls into `decode_attr`:
```
926                     constr = CS(i ? decode_attr(opdstr(n), 0, 0) :
927                         Stringdup(opdstr(n)));
928                     constr->attrs = adj_attr(constr->attrs, attr);
```

Then `decode_attr` function complains that there is an unmatched `@{` and it returns NULL which isn't handled by the calling functions.
